### ISSUE TITLE
Deconvolute Confocal Images

### ISSUE THREAD

**Issue by DrSnail** [computational-imaging/ThreeDeconv.jl#5]
First, Thanks for this awesome package! I am really enjoy it using for widefield images. But i have a little question. Is this package suitable to deconvolute confocal images in Z-stack mode? If the answer is "yes", i should to have psf image generated with depth same as my image depth, and deconvolute each image in "for" cycle?

**Comment by hayatoikoma** [comment]
Thank you for using our package! Yes, you should be able to use it for confocal as long as your imaging condition doesn't have the refractive index mismatch.

You can capture a focal stack with the confocal and simulate (or capture) the 3D psf of the confocal.
Then, you can plug your 3d psf to [here](https://github.com/computational-imaging/ThreeDeconv.jl/blob/master/example/example.jl#L47) and run the 3D deconvolution. (No need to deconvolve each image in a for-loop.)

Since I've never seen how the package works for confocal, it would be great if you can share the results!
